DROP TABLE IF EXISTS films;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS friends;
DROP TABLE IF EXISTS film_genres;
DROP TABLE IF EXISTS genres_names;
DROP TABLE IF EXISTS film_rates;
DROP TABLE IF EXISTS rate_names;

CREATE TABLE IF NOT EXISTS films
(
    id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar(50)  NOT NULL,
    description  varchar(200) NOT NULL,
    release_date date         NOT NULL,
    duration     integer      NOT NULL
    );

CREATE TABLE IF NOT EXISTS users
(
    id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(50) NOT NULL,
    login varchar(50) NOT NULL,
    name  varchar(50) NOT NULL
    );

CREATE TABLE IF NOT EXISTS likes
(
    film_id integer,
    user_id integer
);

CREATE TABLE IF NOT EXISTS friends
(
    user1_id integer,
    user2_id integer,
    status boolean
);

CREATE TABLE IF NOT EXISTS film_genres
(
    film_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_id integer
);

CREATE TABLE IF NOT EXISTS genre_names
(
    id integer,
    name varchar(30)
    );

CREATE TABLE IF NOT EXISTS film_rates
(
    film_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rate_id integer
);


CREATE TABLE IF NOT EXISTS rate_names
(
    id integer,
    name varchar(5)
    );